### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by flaggz** [tripplet/Adium-Steam-IM#10]
09:59:45: DNS resolve complete for api.steampowered.com:443; 1 addresses returned
09:59:45: (Libpurple: dnsquery) IP resolved for api.steampowered.com
09:59:45: (Libpurple: proxy) Attempting connection to 208.64.202.85
09:59:45: (Libpurple: proxy) Connecting to api.steampowered.com:443 with no proxy
09:59:45: (Libpurple: proxy) Connection in progress
09:59:45: (Libpurple: proxy) Connecting to api.steampowered.com:443.
09:59:45: (Libpurple: proxy) Connected to api.steampowered.com:443.
09:59:45: (Libpurple: cdsa) Connecting
09:59:45: (Libpurple: cdsa) Connecting
09:59:45: (Libpurple: cdsa) Connecting
09:59:46: (Libpurple: cdsa) Connecting
09:59:46: (Libpurple: cdsa) SSL_connect: verifying certificate
09:59:46: (Libpurple: cdsa) SSL_connect complete
09:59:46: (Libpurple: steam) post_or_get_ssl_connect_cb
09:59:46: (Libpurple: cdsa) Using cipher c014.
09:59:47: (GLib : general): CRITICAL: xmlnode_get_data: assertion 'node != NULL' failed
09:59:47: (Libpurple: connection) purple_connection_error_reason called with NULL description
09:59:47: (Libpurple: connection) Connection error on 0x6000000b6aa0 (reason: 0 description: Errore sconosciuto)
09:59:47: Connection Disconnected: gc=b6aa0 (Errore sconosciuto)
09:59:47: <ESPurpleSteamAccount:3c2bfd0 9>:**myaccount** accountConnectionReportDisconnect: Errore sconosciuto
09:59:47: (Libpurple: account) Disconnecting account **myaccount** (0x600000142940)
09:59:47: (Libpurple: connection) Disconnecting connection 0x6000000b6aa0
09:59:47: (GLib : general): CRITICAL: purple_url_encode: assertion 'str != NULL' failed
09:59:47: (Libpurple: steam) getting url /ISteamWebUserPresenceOAuth/Logoff/v0001

**Comment by tripplet** [comment]
Which version of the plugin and adium are you using?

**Comment by flaggz** [comment]
adium 1.5.11b2 and steamim 1.8 on osx 10.10.3

**Comment by tripplet** [comment]
Interesting, I'm using the same combination, at everything is working fine.
Maybe something is corrupted in the user settings, can you try it on a guest account to  rule out any corrupted user settings.

**Comment by flaggz** [comment]
Added guest and this happens

![schermata 2015-05-14 alle 11 54 11](https://cloud.githubusercontent.com/assets/7655589/7629798/02fb3408-fa30-11e4-81c6-ac897d667545.png)

**Comment by tripplet** [comment]
This is currently a bug in in adium (#9), I'll ty to write a workaround inside the plugin.

**Comment by tripplet** [comment]
See possible fix on #9

**Comment by flaggz** [comment]
I don't see the new release on the page listed https://github.com/tripplet/Adium-Steam-IM/releases
Last one is the version I have (1.8) released on Oct 29, 2014

**Comment by tripplet** [comment]
Sorry forget to publish, release is now online [v1.81](https://github.com/tripplet/Adium-Steam-IM/releases)

**Comment by flaggz** [comment]
Now i can see the url but the captcha doesn't match. The problem is that every time you reload the url there is a new code.

So the code in the adium window differs from the one in the URL loaded in a browser

**Comment by tripplet** [comment]
Are you sure the captcha is different when you reload the page,
the captcha gets generated every time, but the characters should stay the
same
(At least when I tested it)

2015-05-15 11:38 GMT+02:00 flaggz <notifications@github.com>:

**Comment by flaggz** [comment]
Yep,

copy & paste the URL in a browser then reload the page several times(disable cache).
Every reload is a different captcha

**Comment by tripplet** [comment]
Interesting, on my machine the captcha allways shows the same characters: [screen capture](https://dl.dropboxusercontent.com/u/6430703/steam_captcha.mov)
If you get different characters thats very interesting

**Comment by flaggz** [comment]
sorry, you are absolutely right and I was distracted
the same happens to me but putting the captcha in doesn't work

**Comment by tripplet** [comment]
np, thanks for the detailed log but I'm not quite sure why this is happenin it might be a problem, with the pidginopensteamworks plugin (see issue [here](https://code.google.com/p/pidgin-opensteamworks/issues/detail?id=56) and also the #9.
You should watch these for further progress on the captcha rejection issue.
