### ISSUE TITLE
Improvement: Captcha request dialog showing image

### ISSUE THREAD

**Issue by tripplet** [tripplet/Adium-Steam-IM#12]
Currently the captcha dialog requests the user to open the given url in the browser.
This behaviour was necessary as the lib-purple interface seems to have problems displaying images.

Improvement:
Use a native OSX window to request the captcha from the user.

**Comment by epichub** [comment]
Right now I cannot connect for the same reason, and the only error message i can see is:
"Error: Please verify your humanity by re-entering the characters below."
Launching Adium in debug mode does not output any URL to the logs for me to "solve captcha" in either, so I'm stuck..
