### ISSUE TITLE
Unread messages

### ISSUE THREAD

**Issue by CrimsonSoul** [tripplet/Adium-Steam-IM#14]
Im unsure if this is an open steamworks/steam plugin bug but I figured I'd get your input on this. Every time I reconnect such as waking my macbook from sleep, I got multiple chat popups saying I have hundreds of unread messages. This happens every time regardless of whether the messages are read or not. Its quite the annoyance. It does not seems to affect other chat services. This also doesn't seem to happen until have I've actually started a chat with someone but once I do they are one of the chat windows that pops up when adium connects/reconnects.

**Comment by 07151129** [comment]
This is a bug of pidgin-opensteamworks, something you have to bug its developers about, not @tripplet.

**Comment by CrimsonSoul** [comment]
https://github.com/EionRobb/pidgin-opensteamworks/issues/105 Looks like it was fixed in opensteamworks. Would it be possible to get an update for adium-steam with the new build of opensteamworks?

**Comment by tripplet** [comment]
Done, [v1.10](https://github.com/tripplet/Adium-Steam-IM/releases/tag/v1.10) should fix this.
