### ISSUE TITLE
Add latest Adium versions support

### ISSUE THREAD

**Issue by 07151129** [tripplet/Adium-Steam-IM#8]
Current build will not work with [latest](https://bitbucket.org/adium/adium) Adium version (1.7+) (the reason being newer framework versions which are incompatible with versions this build links to). It would be nice if it got some support.

Necessary changes are:
1. Drop i386 support, since new Adium utilises ARC
2. Build [libjson-glib](https://github.com/GNOME/json-glib) on our own, since Adium does not include it anymore

Adium can also be added to this repo as a submodule. As to json-glib, building it requires spending some fun time with automake, so I suggest to distribute a pre-built library (I can provide it if needed), which we will link against.
I also noticed that we have to keep json-glib.h in ./glib-headers/json-glib/, rather than ./glib-headers.

**Comment by tripplet** [comment]
Where did you find Adium 1.7?

**Comment by comscandiumplumbumd** [comment]
As you can [https://bitbucket.org/adium/adium/src/1e1382dbd8447b1354a4404ac9143aafaa9b624b/Plists/Info.plist?at=default#cl-372](see), latest version is actually 1.7.

**Comment by tripplet** [comment]
Adium is now used as git submodule.
Adium 1.7 support is on the todo list :smirk:

**Comment by comscandiumplumbumd** [comment]
You might want to use git-hg for this, although this is such a pain…

**Comment by comscandiumplumbumd** [comment]
Caught `steam_connection_process_data` crash today (backtrace is posted above). [This](https://gist.github.com/comscandiumplumbumd/18fa95aa3f0fe043572e) is what debugger reports. Looks weird; is this a bug in libjson-glib (or even libglib)?
