### ISSUE TITLE
Steam captcha impossible to solve

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [tripplet/Adium-Steam-IM#9]
Whenever you try to add a new account you get this window. There doesn't seem to be any way to get a captcha to solve, making it impossible to log in.
![selection](https://cloud.githubusercontent.com/assets/1535737/6091119/098107aa-ae61-11e4-8ee7-cbdf842d1056.png)

**Comment by comscandiumplumbumd** [comment]
Are you using adium linked against 10.10's uikit?

**Comment by MisakaImoutoWaifu** [comment]
I just tried versions 1.5.9, 1.5.10, 1.5.11 (Nightly from Jan 15) and 1.6.
1.6 doesn't seem to work with the plugin at all while each 1.5.x version gives the captcha issue. 
I forgot to mention I am using Yosemite 10.10.2.

**Comment by comscandiumplumbumd** [comment]
For the plugin to work with newer versions of Adium, you have to link it against new frameworks (bundled with Adium source).
On 1.7 (osx 10.9) I get no captcha window when adding a new account, but if I try to log in with a wrong password, status changes to 'network offline' and that's it. Weird.

**Comment by tripplet** [comment]
This is most likely a bug in the libpurple to adium interface, the code to display the captcha window looks comes from the pidgin-opensteamworks project.
I'll try it on a windows machine the next time I get a hold on one to verify its not a bug in the pidgin-opensteamworks code.

Workaround:
Just try to wait some time or login via the website to get rid of the captcha in adium.

**Comment by tripplet** [comment]
Verified, it's a bug in libpurple to adium interface; Windows is working fine.
I'll try to look into it and report it to adium.
[Affected function](https://github.com/tripplet/pidgin-opensteamworks/blob/master/steam-mobile/libsteam.c#L250-L276)

**Comment by tripplet** [comment]
I made a workaround, which displays the captcha url instead of the image.
Oddly for me this is not working properly, the captcha gets rejected.
Maybe someone else can verify this behaviour?
https://github.com/tripplet/Adium-Steam-IM/releases

**Comment by cosmojasra** [comment]
Yeah, i got the same problem. I downloaded your beta release 1.81 and get the captcha window. It shows a link which I open in Safari, but when I enter the captcha and click OK, the window opens all over again.

**Comment by ofus** [comment]
My captcha is being repeatedly rejected using the 1.81 urls also ;_;

**Comment by tripplet** [comment]
The captcha rejection might be a problem with the underlying pidgin-opensteamworks (issue [here](https://code.google.com/p/pidgin-opensteamworks/issues/detail?id=95)).
For solving the captcha display problem, I'm working on a osx dialog, but this seems to be not as easy as I first thought, hence the copy/paste solution.

**Comment by tripplet** [comment]
Fix is live (thanks to Eion Robb's fix in pidgin-opensteamworks) 
New version 1.9 [here](https://github.com/tripplet/Adium-Steam-IM/releases/tag/v1.9)

**Comment by ofus** [comment]
Thank you

**Comment by tripplet** [comment]
As no one is complaining about new bugs, issue closed.
